### ISSUE TITLE
PyHEP 2022 "proceedings"

### ISSUE THREAD

**Issue by eduardo-rodrigues** [ComPWA/PyHEP2022#1]
Hello @redeboer, I see that you already have a DOI for your PyHEP 2022 talk. Can you then "attach it" in Zenodo to the pyhep2022 community so as to be part of the "proceedings"? I will get a ping to curate and accept.

Also, I see that Indico has Google slides for the talk. Can you upload to Indico a PDF for posterity?

Many thanks.

**Comment by eduardo-rodrigues** [comment]
Also nicer if you update the title of the Zenodo page to the actual talk title ;-).

**Comment by redeboer** [comment]
Hi @eduardo-rodrigues, thanks for the reminder, I overlooked the zenodo community!

> Also, I see that Indico has Google slides for the talk. Can you upload to Indico a PDF for posterity?

Done :heavy_check_mark:

**Comment by eduardo-rodrigues** [comment]
Hi. I do not know what happened but I got a request to curate from Zenodo but when I log in to accept your contribution in the pyhep2022 community I see no request. As if it got retracted somehow? As you can see from https://zenodo.org/record/7133249 the entry is not attached to any community. Sorry for the hassle but an you check what is going on?

**Comment by redeboer** [comment]
Hmm curious. It's probably because I made a new release at the same time (just some dependency pinning changes). I'll add the pyhep community again, let me know if it works

**Comment by eduardo-rodrigues** [comment]
I got it now.

No idea what happened. It is likely a bug in Zenodo since a new release implies a new DOI hence it should not interfere with the request for a different entry/DOI, even if from the same source=repository.

Anyway, sorted now.
